FROM node:20-alpine

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

USER node

RUN npm ci

COPY --chown=node:node . .

EXPOSE 3000

CMD ["node", "src/index.js"]