apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-secret
spec:
  refreshInterval: {{ .Values.vault.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Chart.Name }}-secret
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.vault.path }}
        property: host
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.vault.path }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.vault.path }}
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.vault.path }}
        property: database