{{- if (default false .Values.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default .Chart.Name .Values.serviceAccount.name }}
  annotations:
    {{- toYaml (default dict .Values.serviceAccount.annotations) | nindent 4 }}
{{- end }}