replicaCount: 2

image:
  repository: "620969609526.dkr.ecr.ap-southeast-1.amazonaws.com/eks/my-app"
  tag: "v1.0.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000


ingress:
  enabled: true
  className: alb
  # host: my-app.example.com
  
env:
  NODE_ENV: production
  APP_PORT: "3000"

vault:
  enabled: true
  secretStoreName: vault-backend
  path: secret/data/dev/aurora
  refreshInterval: 1h

serviceAccount:
  create: false
  name: default
  annotations: {}

httpRoute:
  enabled: false
  parentRefs: []
  hostnames: []